# Generated by Django 3.1.1 on 2020-09-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200928_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.JSONField(null=True),
        ),
    ]
